-- Create pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Table for storing raw stock data
CREATE TABLE IF NOT EXISTS stock_data (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10),
    timestamp TIMESTAMP,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    volume FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, timestamp)
);

-- Index for fast lookups by symbol and time
CREATE INDEX IF NOT EXISTS idx_stock_symbol_timestamp ON stock_data(symbol, timestamp);

-- Table for storing vector embeddings for RAG
CREATE TABLE IF NOT EXISTS stock_embeddings (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10),
    timestamp TIMESTAMP,
    day_of_week INTEGER, -- 0 = Sunday, 6 = Saturday
    hour INTEGER,
    price_change_pct FLOAT,
    volume_change_pct FLOAT,
    embedding vector(1536), -- Vector type for embeddings
    metadata JSONB DEFAULT '{}', -- Use JSONB for metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, timestamp)
);

-- Create an index for vector similarity search
CREATE INDEX IF NOT EXISTS idx_stock_embeddings_vector ON stock_embeddings USING ivfflat (embedding vector_l2_ops);

-- Table for storing chat messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255), -- Can be anonymous or user identifier
    message_text TEXT,
    is_bot BOOLEAN, -- True for bot messages, False for user messages
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for storing stock analyses generated by the bot
CREATE TABLE IF NOT EXISTS stock_analyses (
    id SERIAL PRIMARY KEY,
    chat_id VARCHAR(255), -- To link multiple analyses in the same conversation
    title TEXT,
    content TEXT,
    symbols TEXT[], -- Array of stock symbols analyzed
    time_period VARCHAR(50), -- e.g., "1h", "1d"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_stock_analyses_symbols ON stock_analyses USING gin(symbols);
